name: Linux OpenVPN3 GUI

on:
  workflow_dispatch:

jobs:
  build-linux-native:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:

          # --------------------
          # Ubuntu
          # --------------------
          - name: Ubuntu 22.04 amd64
            runner: ubuntu-22.04
            qt_arch: linux_gcc_64
            qt_version: 6.10.1
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++

          - name: Ubuntu 24.04 amd64
            runner: ubuntu-24.04
            qt_arch: linux_gcc_64
            qt_version: 6.10.1
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++

          # - name: Ubuntu 22.04 arm64
          #   runner: ubuntu-22.04-arm
          #   qt_arch: linux_gcc_arm64
          #   qt_version: 6.8.3
          #   build_type: Release
          #   c_compiler: gcc
          #   cpp_compiler: g++

          - name: Ubuntu 24.04 arm64
            runner: ubuntu-24.04-arm
            qt_arch: linux_gcc_arm64
            qt_version: 6.10.1
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    
    - name: Install Wayland
      run: | 
            sudo apt install qt6-wayland
            sudo apt install libwayland-dev libwayland-egl1-mesa libwayland-server0 libgles2-mesa-dev libxkbcommon-dev
            export QT_QPA_PLATFORM=wayland

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.3.*'
        version: ${{ matrix.qt_version }}
        target: desktop
        arch: ${{ matrix.qt_arch }}
        modules: qtwayland


    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    
    - name: Install LinuxDeploy
      id: install-linuxdeploy
      uses: miurahr/install-linuxdeploy-action@v1.8.0
      with:
        dir: ${{ github.workspace }}
        plugins: qt 

    - name: Run LinuxDeploy
      shell: bash
      run: |
        TOOL_DIR="${{ github.workspace }}"
        APPDIR="${{ steps.strings.outputs.build-output-dir }}"
        EXTRA_PLATFORM_PLUGINS: "wayland"
        ARCH_SUFFIX=$(uname -m)
        
        LINUXDEPLOY_BIN="$TOOL_DIR/linuxdeploy-$ARCH_SUFFIX.AppImage"
        
        $LINUXDEPLOY_BIN --appdir "$APPDIR" \
          -d "${{ github.workspace }}/deploy/openvpn3-gui.desktop" \
          -i "${{ github.workspace }}/resources/img/logo-modified.png" \
          -e "$APPDIR/app" \
          --plugin qt 

    - name: Filter system libraries and docs
      shell: bash
      run: |
        APPDIR="${{ steps.strings.outputs.build-output-dir }}/usr"
    
        echo "Filtering libraries in $APPDIR/lib..."
        for lib in "$APPDIR/lib"/*.so*; do
          [ -e "$lib" ] || continue
          base=$(basename "$lib")
          if ldconfig -p | grep -q "$base"; then
            echo "SYSTEM LIBRARY: $base → removing"
            rm -f "$lib"
          else
            echo "BUNDLE: $base"
          fi
        done
    
        echo "Filtering documentation in $APPDIR/share/doc..."
        for doc in "$APPDIR/share/doc"/*; do
          [ -e "$doc" ] || continue
          name=$(basename "$doc")
          if [ -e "/usr/share/doc/$name" ]; then
            echo "SYSTEM DOC: $name → removing"
            rm -rf "$doc"
          else
            echo "BUNDLE DOC: $name"
          fi
        done

    - name: Create tarball
      shell: bash
      run: |
        BUILD_DIR="${{ steps.strings.outputs.build-output-dir }}"
        ARCHIVE_NAME="OpenVPN3-GUI-${{ matrix.name }}.tar"

        tar -cvf "$ARCHIVE_NAME" -C "$BUILD_DIR" usr
          
    - name: Upload tarball artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenVPN3-GUI-${{ matrix.name }}
        path: OpenVPN3-GUI-${{ matrix.name }}.tar
        if-no-files-found: error

  # build-linux-containers:
  #   name: ${{ matrix.name }}
  #   runs-on: ${{ matrix.runner }}
  #   container: ${{ matrix.container  }}

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       build_type: [Release]
  #       include:

  #         # --------------------
  #         # Ubuntu
  #         # --------------------

  #         - name: Ubuntu 25.04 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: ubuntu:25.04
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: Ubuntu 25.04 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: ubuntu:25.04
  #           c_compiler: gcc
  #           cpp_compiler: g++
  #         # --------------------
  #         # Debian
  #         # --------------------
  #         - name: Debian 12 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: debian:12
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: Debian 12 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: debian:12
  #           c_compiler: gcc
  #           cpp_compiler: g++
            
  #         - name: Debian 13 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: debian:13
  #           c_compiler: gcc
  #           cpp_compiler: g++
          
  #         - name: Debian 13 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: debian:13
  #           c_compiler: gcc
  #           cpp_compiler: g++


  #         # --------------------
  #         # Fedora
  #         # --------------------
  #         - name: Fedora 41 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: fedora:41
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: Fedora 41 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: fedora:41
  #           c_compiler: gcc
  #           cpp_compiler: g++
            
  #         - name: Fedora 42 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: fedora:42
  #           c_compiler: gcc
  #           cpp_compiler: g++
          
  #         - name: Fedora 42 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: fedora:42
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         # --------------------
  #         # RHEL (UBI images)
  #         # --------------------
  #         - name: RHEL 8 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: registry.access.redhat.com/ubi8/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: RHEL 9 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: registry.access.redhat.com/ubi9/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: RHEL 10 amd64
  #           runner: ubuntu-24.04
  #           qt_arch: linux_gcc_64
  #           container: registry.access.redhat.com/ubi10/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: RHEL 8 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: registry.access.redhat.com/ubi8/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: RHEL 9 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: registry.access.redhat.com/ubi9/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #         - name: RHEL 10 arm64
  #           runner: ubuntu-24.04-arm
  #           qt_arch: linux_gcc_arm64
  #           container: registry.access.redhat.com/ubi10/ubi
  #           c_compiler: gcc
  #           cpp_compiler: g++

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set reusable strings
  #     # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
  #     id: strings
  #     shell: bash
  #     run: |
  #       echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
  #   - name: Install build dependencies (Linux containers)
  #     shell: bash
  #     run: |
  #       if command -v apt-get >/dev/null; then
  #         apt-get update
  #         apt-get install -y build-essential cmake ninja-build
  #       elif command -v dnf >/dev/null; then
  #         dnf install -y gcc gcc-c++ cmake ninja
  #       elif command -v microdnf >/dev/null; then
  #         microdnf update -y
  #         microdnf install -y gcc gcc-c++ cmake ninja
  #       fi

  #   - name: Install Qt
  #     uses: jurplel/install-qt-action@v4
  #     with:
  #       aqtversion: '==3.1.*'
  #       version: '6.8.3'
  #       target: desktop
  #       arch: ${{ matrix.qt_arch }}

  #   - name: Configure CMake
  #     # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
  #     # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
  #     run: >
  #       cmake -B ${{ steps.strings.outputs.build-output-dir }}
  #       -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
  #       -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
  #       -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
  #       -S ${{ github.workspace }}

  #   - name: Build
  #     run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
