name: Windows OpenVPN3 GUI

on:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:

          # --------------------
          # Windows
          # --------------------
          - name: Windows 11 amd64
            runner: windows-2025
            msvc_arch: amd64
            qt_arch: win64_msvc2022_64
            qt_version: 6.10.1
            c_compiler: cl
            cpp_compiler: cl
            cmake_arch: x64
            build_type: Release

          # - name: Windows x86
          #   runner: windows-latest
          #   msvc_arch: amd64_x86     
          #   qt_arch: win32_msvc2019
          #   qt_version: 5.15.2
          #   c_compiler: cl
          #   cpp_compiler: cl
          #   cmake_arch: Win32   
          #   build_type: Release

          - name: Windows 11 arm64
            runner: windows-2025
            msvc_arch: amd64_arm64
            qt_arch: win64_msvc2022_arm64_cross_compiled
            qt_version: 6.9.1
            c_compiler: cl
            cpp_compiler: cl
            cmake_arch: ARM64
            build_type: Release

          - name: Windows 10 amd64
            runner: windows-2022
            msvc_arch: amd64
            qt_arch: win64_msvc2022_64
            qt_version: 6.10.1
            c_compiler: cl
            cpp_compiler: cl
            cmake_arch: x64
            build_type: Release

          - name: Windows 10 arm64
            runner: windows-2022
            msvc_arch: amd64_arm64
            qt_arch: win64_msvc2022_arm64_cross_compiled
            qt_version: 6.9.1
            c_compiler: cl
            cpp_compiler: cl
            cmake_arch: ARM64
            build_type: Release

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

        
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          aqtversion: '==3.3.*'
          py7zrversion: '==1.0.*'
          arch: ${{ matrix.qt_arch }}

      - name: Configure CMake (Windows)
        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} `
            -S ${{ github.workspace }} `
            -A ${{ matrix.cmake_arch }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Deploy (Windows ARM64)
        if: matrix.cmake_arch == 'ARM64'
        shell: pwsh
        run: |
          & "$env:QT_HOST_PATH\bin\windeployqt.exe" `
            --qtpaths "$env:QT_ROOT_DIR\bin\qtpaths.bat" `
            ${{ steps.strings.outputs.build-output-dir }}\Release\app.exe

      - name: Deploy (Windows amd64 and Win32)
        if: matrix.cmake_arch == 'x64' || matrix.cmake_arch == 'Win32'
        run: |
          windeployqt "${{ steps.strings.outputs.build-output-dir }}\Release\app.exe"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenVPN3-GUI-${{ matrix.name }}
          path: ${{ steps.strings.outputs.build-output-dir }}\Release\

